AWSTemplateFormatVersion: "2010-09-09"
Description: "Plantilla para crear una Maquina Virtual en EC2 usando una AMI especifica (Cloud9Ubuntu22-2024-10-03T14-39)"

Parameters:
  # InstanceName:
  #   Type: String
  #   Default: "MV Ciencia Datos"
  #   Description: "Nombre de la instancia a crear"
  AMI:
    Type: String
    Default: "ami-058a5ce591396c41b"
    Description: "ID de AMI"
  
Resources:
  EC2InstanceDev:
    Type: "AWS::EC2::Instance"
    Properties:
      Tags:
        - Key: "Name"
          Value: "MV DEV Ciencia Datos"
      ImageId: !Ref AMI
      InstanceType: "t2.medium"
      KeyName: "vockey"
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: "20"
    
  EC2InstanceTest:
    Type: "AWS::EC2::Instance"
    Properties:
      Tags:
        - Key: "Name"
          Value: "MV TEST Ciencia Datos"
      ImageId: !Ref AMI
      InstanceType: "t2.medium"
      KeyName: "vockey"
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: "20"
    
  EC2InstanceProd:
    Type: "AWS::EC2::Instance"
    Properties:
      Tags:
        - Key: "Name"
          Value: "MV PROD Ciencia Datos"
      ImageId: !Ref AMI
      InstanceType: "t2.medium"
      KeyName: "vockey"
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: "20"

  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Abrir 8081 para MySQL"
      GroupName: "SG-mv-ciencia-datos"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"
          # MySQL port
        - IpProtocol: "tcp"
          FromPort: "8081"
          ToPort: "8081"
          CidrIp: "0.0.0.0/0"

Outputs:
  DevInstanceId:
    Description: "ID de la instancia EC2 DEV"
    Value: !Ref EC2InstanceDev
  DevInstancePublicIP:
    Description: "IP publica de la instancia DEV"
    Value: !GetAtt EC2InstanceDev.PublicIp
  TestInstanceId:
    Description: "ID de la instancia EC2 TEST"
    Value: !Ref EC2InstanceTest
  TestInstancePublicIP:
    Description: "IP publica de la instancia TEST"
    Value: !GetAtt EC2InstanceTest.PublicIp
  ProdInstanceId:
    Description: "ID de la instancia EC2 PROD"
    Value: !Ref EC2InstanceProd
  ProdInstancePublicIP:
    Description: "IP publica de la instancia PROD"
    Value: !GetAtt EC2InstanceProd.PublicIp